export const BASE_URL = "http://62.84.187.91:3000/"
export const USER_URL = "api/user"
export const ROOM_URL = "api/room"
export const CHANEL_URL = "api/chanel"
export const MESSAGE_URL = "api/message"